### ISSUE TITLE
Ongoing Verification Issues -- Android,iOS : ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3280]
**Frequency:** 100%
**Android App version:** Android Celo Alfa v1.6.2 (104794504)
**Repro on Android Device:** Samsung Galaxy J7 Prime (6.0.1)

**Repro Steps:** 
1) Launch the app and Perform sign up flow
2) Navigate to verification flow 
3) Try to paste the code and Observe

**Current Behavior:** ‘Verification Error’ popup is shown while verifying verification code

**Expected Behavior:** ‘Verification Failed’ & ‘Verification Error’ popup should be not shown and account should be verified 

**Impact:** User is unable to verify the account 

**Attachment:**  [Android_Verification failed error message is shown.mp4](https://drive.google.com/file/d/1SNfjcVGuKTKvAiOZPerc8TuC-J-cRkZU/view?usp=sharing) (Bug observed between 1:22 to 2:16 mins)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS test flight build : v1.6.2 (25). Verified on Device : iPhone 6+ (12.4.5) and observed that issue is also reproduce in iOS. 'Verification Failed' & 'Verification Error' popup is shown while verifying the phone number.

Attachment : [iOS_Verification failed error message is shown](https://drive.google.com/file/d/1ZRucWpEKgL8zPkbXsZZkqACNWbpDtVlH/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified issue on Android build 1.7.0 (104894304) and observed that issue is still repro and also observed that user did not get initial escrow payments. 

- ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number
Attachment: [Verification_Fail.mp4](https://drive.google.com/file/d/1FxCzK3cAhxLZEPyOxdEN_gL5qeNTwK2z/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified issue with latest Android build Android Celo Alfa build : v1.7.1 and observed that issue is still reproduced: 
- Android : ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number

Attachment: [Android_PhoneNumberVerification.mp4 ](https://drive.google.com/file/d/1F1YOIObXQC9zu1i7XhJB33NLgV6T4w42/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified issue with latest iOS Test flight build : 1.7.1 (28) and observed that issue is still reproduced:

‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number

Attachment: [iOS_Verification failed error message.mp4](https://drive.google.com/file/d/1tIcgYUiXAbvt5Wmnb3_DqKn7HQqBEjG9/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Here are the iOS device logs. 'Verification failed' error is shown while verifying the phone number.

Attachment : [iOS device log for verification failed.rtf](https://drive.google.com/file/d/1i1uiBf_POt0Z1HD0Jg0p803uN7RPLTmd/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit Those are the general phone logs. In general, when we request logs, we mean the Celo App logs, which can be collected from the Settings page

**Comment by Lss-Ankit** [comment]
@jmrossy 'Report' option is no longer available in android & iOS app. Verified on Android Celo Alfa build : v1.7.1 & iOS Test flight build : 1.7.1 (28). So, i am unable to take log from Settings page.
Attachment for 
android : [Android_Report option is not shown](https://drive.google.com/file/d/1thZdQgyR9w9OhoJosgoutUGDAAy2E9fo/view?usp=sharing) 
Attachment for iOS : [iOS_Report option is not shown](https://drive.google.com/file/d/1JimY7mebDX7WCtjuTWUkKNPJbVHH8q6W/view?usp=sharing)

I have taken app log form device settings > analytics data. Here are the device log. 
Device log: [Celo_device_app log](https://drive.google.com/file/d/1XRzcsRIeMTKkgGwNIoVSLWiyhVO44Hu6/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit The 'Report' option is now called 'Support'

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the update. I have taken a log from support > contact us. Here the app log which having 'Verification failed' error while verifying the phone number 
Attachment : [iOS_Device log_Verification failed](https://drive.google.com/file/d/1JHriVKNEsoODa36InHF-4NuhOiqnTxuM/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit Thanks for sharing those logs.
It seems that verification failed because a transaction timed out. That's surprising because the limit of 40 seconds should be more than enough time for each transaction. Do you generally have any internet connectivity issues or is your connection solid? And does the app sometimes show the 'Connecting' banner?

**Comment by Lss-Ankit** [comment]
@jmrossy Yes,i can say my connection is solid. 
No ,i did not see 'Connecting' banner while performing testing.

**Comment by jmrossy** [comment]
@Lss-Ankit Thanks for clarifying! We are investigating a fix now.

**Comment by Lss-Ankit** [comment]
Hi @annakaz and @jmrossy Today i have again verified issue using Android build Celo (Dev)_1.7.1 (101748676) and observed that issue is still reproduced. 

Please find an attachmnet and logs for the same. 
Attachment: [VerificationFailed.mp4](https://drive.google.com/file/d/1DA3z3jGlztHjs3PbZpCqwh227WN2QX-8/view?usp=sharing) 
Logs: [celo_logs (1).txt](https://github.com/celo-org/celo-monorepo/files/4586680/celo_logs.1.txt)

**Comment by annakaz** [comment]
Note the logs from the comment above are now linked to issue #3747. The logs from this issue can be found at: https://celo-org.slack.com/files/UN7CEV7ED/F013059MA22/celo_logs_verificationfailed.txt?origin_team=T9SEZ6M9B&origin_channel=CNCUN1R0D

**Comment by Lss-Ankit** [comment]
Hi @annakaz i have verified the issue with retrive data Saver and found that issue is still reproduced. 
- User is not able to verify the phone number even after user try with Retry with data saver button once verification is failed first time.  
Attachment: [VerificationIssue.mp4](https://drive.google.com/file/d/1bQw7hx4oFsx0XxtDmVqDPUfQSdTLdONA/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @annakaz Please find the log for the above failure: 

Attachment: 
[celo_logs_RetryWithDataSaver.txt](https://github.com/celo-org/celo-monorepo/files/4665975/celo_logs_RetryWithDataSaver.txt)

**Comment by Lss-Ankit** [comment]
@nityas @jmrossy @annakaz  i have verified this issue again on Android build 1.8.0 (104994308) and found the following: 
- Issue is repro for devices: Samsung Galaxy M30S (9.0), Samsung Note 9 (10),Pixel XL 2 (10), Google pixel Xl (8.1)
- issue does not repro for devices: Samsung Galaxy A50	(9.0),Samsung Galaxy A70 (9.0), Samsung 
Galaxy M30S (9.0)
Attachment: https://drive.google.com/file/d/19qjt58u2SREt66nWtsUt652pIJ_8KwzV/view?usp=sharing
Logs: 
[Verificationfail.txt](https://github.com/celo-org/celo-monorepo/files/4667634/Verificationfail.txt)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android play store (Internal build) v1.8.2 and observed that issue is still reproduced. 

Attachment: [Verificationfail.mp4](https://drive.google.com/file/d/1E1BpnV708aRB4zo3fw0uwbP-aUDHRvSe/view?usp=sharing)
Logs: [celo_logs (2).txt](https://github.com/celo-org/celo-monorepo/files/4688271/celo_logs.2.txt)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight Valora build v1.0.0(6) and observed that issue is reintroduced
- ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.
- **Device Used:**  iPhone 6(12.4.7)
![VerficationErrorIssue](https://user-images.githubusercontent.com/55572027/88905367-d4b62400-d273-11ea-9d15-5522593dbfdb.PNG)

**Comment by Lss-Ankit** [comment]
@annakaz Verified with Android Valora app build v1.0.0 (11) & IOS test flight build v1.0.0 (11) and found that issue is still reproduced. 
- ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.
Note: i have try with retry with data saver, but still  facing same error. 
Device:Google Pixel Xl (8.1) | iPhone 6+ (12.4.5)

**Comment by Lss-Ankit** [comment]
@annakaz Verified with latest Android Valora app build v1.0.0 (12) but still not able to verify the phone number. 

- ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.
Device:Google Pixel Xl (8.1)

**Comment by Lss-Ankit** [comment]
@annakaz  Verified with latest Test flight build v1.0.0 (15) and Android build v1.0.0 (14) and found that issue is still reproduced as getting Verification Error’ popup while verifying the phone number hence not able to verify the phone number 

Verified devices:  iPhone 7+ (13.3.1) | Google Pixel Xl (8.1)

**Comment by Lss-Ankit** [comment]
I have verified this issue with latest Play store build v1.01 and App store v1.0.1 and observe issue is still reproduce some times. 

- ‘Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.
- Some time i am navigating to enter three screen code but but not getting Auth codes. 
- Some time i got only 2 Auth codes instead of 3 Auth codes. 

**Verified on devices:** iPhone 11 (14 beta 6),Samsung Galaxy A5(7.0)

**Comment by tarikbellamine** [comment]
@i1skn assigning to you because you're closest to this at the moment. feel free to close if you believe it is no longer relevant.

**Comment by i1skn** [comment]
Closing this as this should be fixed already.

**Comment by Lss-Ankit** [comment]
Hey @gnardini , @i1skn  i have observed issue while perform testing using Android play store internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27) 

Issue observed for three times while verifying the phone number. Also, tried after enabling the data saver toggle but still facing same issue. 
2 time we are able to verify phone number.  

For now i am reopening this ticket. 

For that i have taken logs which may help you. 
Logs: 
[celo_logs.txt](https://github.com/celo-org/celo-monorepo/files/5439019/celo_logs.txt)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified task using Test flight build v1.4.0 (28) and Android play store (internal build) v1.4.0 (1004294317) and found that user is able to complete phone number verification flow with out facing any verification failed pop up. 

Verified on : iPhone XR (13.2.2) and Google Pixel XL (8.1)

**Comment by Lss-Ankit** [comment]
Hi @gnardini @nityas @jeanregisser  We have verified issue with latest Test flight build v1.9.0 (41) and Android play store internal build 1.9.0 and observed that issue is reintroduced. 

- Verification Failed’ & Verification Error’ popup is shown while verifying the phone number.

[Attachment](https://drive.google.com/file/d/1xrN6tYK7rP3i7WuZiTcYMOOmndnaITtJ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hey @i1skn  I have performed verification flow using latest Android Internal Build V1.9.2(1004294333) & Test Flight Build V1.9.2(43)  & observed that we can able to perform verification flow. Also we have observed below observations.
**For iOS:**

- User gets Verification error message when user try to perform verification while login with new account & from Confirm Now CTA. 
**Note:** We observed this issue when we performing whole process without any major time gap.

- But able to perform verification without error message from setting.

**Frequency:** 40%

**For Android:**
- User able to complete whole verification process in all three scenarios without any error.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR(13.1.3)

**Comment by i1skn** [comment]
So, do I understand correctly that on iOS it sometimes failing only when you initiate verification from "Confirm Now" notification? Is possible to get logs when it does fail this way?

**Comment by tarikbellamine** [comment]
I think this is related to the verification errors we discussed specific to 1.9.0, which we have fixed for the newest release candidate. I believe 1.9.2 has bot seen this issue reproduced. Is this correct @lss-ankit?

**Comment by Lss-Ankit** [comment]
Hey @i1skn , @tarikbellamine I have verified this issue using latest Android Internal Build V1.9.2(1004294333) & Test Flight Build V1.9.2(44) & we have not observed any Verification fail in all scenario i.e. from While login with new account, From Confirm now CTA, Confirm Phone Number from setting & from Earn Rewards pills. In future if we observe any issue then we will update ticket for same.
**Verified on Devices:** iPhone SE(13.4.1), iPhone XR (13.1.3) , Samsung Galaxy A5(7.0)

**Comment by ValoraQA** [comment]
Hi @i1skn @tarikbellamine  I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that we are blocked for this issue.

**Observations:**
- In latest build we have observed that user not able to get any attestation messages. For now we have blocked to test this this issue.  In future we will update issue according to our observations.
FYI: We have raised #[65](https://github.com/celo-org/wallet/issues/65) issue for not receiving codes.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.4.1)

**Comment by i1skn** [comment]
Yeah, expect #65 to be resolved in the 1.11.1! Thanks for raising awareness to this!

**Comment by ValoraQA** [comment]
Hi @i1skn I have verified this issue using latest Android internal build V1.11.1(1004294338) & Test Flight Build V1.11.1(48) & observed following:
**Observations:**

- **For Android:** It is observed that, user get Verification error popup while pasting last attestation code. 

- **For iOS:** It is observed that user get error while pasting first attestation code. 

Hence reopening this ticket.

**Frequency:** 80%
**Verified on devices:**  Samsung Galaxy A5(7.0), iPhone SE (13.4.1)
**Attachment:** [VerificationErrorWhilePastingLastCode.mp4](https://drive.google.com/file/d/1KixTWK_xn-CpIu5vd_oFy31Zh6v9ujNq/view?usp=sharing)
**Logs:** [Android_Logs.txt](https://drive.google.com/file/d/1W7aK7ZKcuXjor1VoQj_TRsHsZfuXD4-Q/view?usp=sharing)

**Comment by i1skn** [comment]
Hey @Celoqa, I'm not able to reproduce this bug on neither iOS neither Android devices. Also, I see that on the video there is an error happens even before the "enter code screen" appears, but in the description you've mentioned that the error appears on the "enter code screen".  `Android_Logs.txt` does not provide much info as well. Can you please try to reproduce it and capture again the screen video as well as logs? Thanks!

**Comment by ValoraQA** [comment]
Hi @i1skn Here is detailed attachment using latest Android internal build V1.11.1(1004294338) & Test Flight Build V1.11.1(48).
**Observations:** 

- **For Android:** We have observed error while pasting last attestation code. This time frequency is 40%.
**Attachment:** [VerificationError.mp4](https://drive.google.com/file/d/1BvB75z6ILqu0FK25nr7v76bKqy95NO3d/view?usp=sharing)
**Logs:** [Android_Logs.txt](https://drive.google.com/file/d/1ug3VC41h86v859UZWChFZ8X-tvTM3nro/view?usp=sharing)
- **For iOS:** Now we have not observed any error while confirming phone number.
**Verified on devices:** Samsung Galaxy A5(7.0), iPhone SE (13.4.1)

**Comment by jeanregisser** [comment]
Should be fixed in 1.15.
Please reopen if it comes back ;)

**Comment by ValoraQA** [comment]
Hi @jeanregisser We have verified this issue on latest builds Android internal V1.15.1 & Testflight build V1.15.1(64) and not observed any verifications issues.
Sure we will open this issue if comes back in future.
