### ISSUE TITLE
“Incorrect PIN” Message is shown when user taps on < back from Enter PIN screen while proceeding to withdraw CELO 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5863]
**Frequency:** 100%
**Repro on build version:** v1.5.2 (31) and Play store internal build 1.5.2 (1004294320)
**Repro on devices:** iPhone SE 2 (14.1) , Google Pixel (8.1) 
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on hamburger menu 
3. Tap on CELO. 
4. Tap on Withdraw CELO
5. Paste Address and enter Amount. 
6. Tap on the Review button. 
7. Tap on the Withdraw button. 
8. Tap on < from enter PIn screen
9. Observed. 

**Current Behavior:**  “Incorrect PIN” Message is shown
**Expected Behavior:**  Transaction fail appropriately message should be shown 
**Investigation:** User is not able  to proceed to send CELO after navigating back from enter PIN 
**Impact:** Bad user experience, Inappropriate message is shown 
**Attachment:**  [Inccorect_Pin.mp4](https://drive.google.com/file/d/1IWrf9cBPGyIgcaDgKLcdGUI56_d6toWP/view?usp=sharing)(Bug observed at sec)

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser I have verified this issue using App store build v1.5.5 & Android play store build v1.5.5 & observed that issue is still reproduced.
**Repro on devices:** iPhone SE (13.5.1), Samsung Galaxy A5(7.0)

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified this issue using latest Android internal build v1.6.0(1004294325) & Test Flight Build v1.5.1(36) and observe issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (13.5.1)
**Observation:** Also observed same issue while buying/selling CELO.

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified this issue using latest Android internal build v1.6.0(1004294326) & Test Flight Build v1.5.1(37) and observe issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (13.5.1)
**Observation:** Also observed same issue while buying/selling CELO.

**Comment by gnardini** [comment]
Fixed by #6002

**Comment by Lss-Ankit** [comment]
@gnardini Verified issue with Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and found the following: 

- [ ] Verified user is redirect to "Review Withdraw" without any error message  screen when user taps on < Arrow from enter PIN screen . 
Can you please confirm is it expected behavior as there no error message is shown like transaction failed. 

-  [ ] Verified user is able to Withdraw CELO after navigating back to Review Withdraw screen by tapping on < Arrow from Enter Screen 

- [ ] Verified user is able to Withdraw CELO again after completing Withdraw CELO once. 

Device: iPhone SE 2 (14.2), Google PIxel XL (8.1)

For now i am reopening this ticket if 1st is expected behavior for now then we can close this ticket. 

Thank!!

**Comment by gnardini** [comment]
Hi @Lss-Ankit yes, the first is expected. The button to confirm should be available after pressing the < button, so if the user wants to go through with the withdrawal they should be able to press the confirm button and do it by putting in their PIN.

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified this issue using latest Android Internal Build V 1.10.1(1004294336) & Test Flight Build V1.10.1(46)  & observed below observation.
**Observations:**

- [x] User able to see "PIN Necessary" validation message when user taps on < arrow from enter PIN screen from Buy/Sell CELO.
- [ ]  User not able to see any validation message when user taps on < arrow on enter PIN screen from Account key after & before Set up, While Confirming Phone Number, Withdrawing CELO.
**Verified on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (14.2)

**Comment by Celoqa** [comment]
Hi @gnardini We have verified this issue on latest builds android internal build V1.15.2 & Testflight build V1.15.12(65) and observe issue is still repro.
- User not able to see any validation message when user taps on < arrow on enter PIN screen from Withdrawing CELO.
**Devices:** iPhone 6 + (12.4.5), Vivo V11 pro (10)
